// Generated by dts-bundle v0.7.3
export interface IncomingResponse {
    /** The incoming message. */
    readonly message: IncomingResponseMessage;
}
export declare class IncomingResponseMessage extends IncomingMessage {
    statusCode: number | undefined;
    reasonPhrase: string | undefined;
    constructor();
}
export declare class IncomingMessage {
    viaBranch: string;
    method: string;
    body: string;
    toTag: string;
    to: any;
    fromTag: string;
    from: any;
    callId: string;
    cseq: number;
    via: {
        host: string;
        port: number;
    };
    headers: {
        [name: string]: Array<{
            parsed?: any;
            raw: string;
        }>;
    };
    referTo: string | undefined;
    data: string;
    /**
     * Insert a header of the given name and value into the last position of the
     * header array.
     * @param name - header name
     * @param value - header value
     */
    addHeader(name: string, value: string): void;
    /**
     * Get the value of the given header name at the given position.
     * @param name - header name
     * @returns Returns the specified header, undefined if header doesn't exist.
     */
    getHeader(name: string): string | undefined;
    /**
     * Get the header/s of the given name.
     * @param name - header name
     * @returns Array - with all the headers of the specified name.
     */
    getHeaders(name: string): Array<string>;
    /**
     * Verify the existence of the given header.
     * @param name - header name
     * @returns true if header with given name exists, false otherwise
     */
    hasHeader(name: string): boolean;
    /**
     * Parse the given header on the given index.
     * @param name - header name
     * @param idx - header index
     * @returns Parsed header object, undefined if the
     *   header is not present or in case of a parsing error.
     */
    parseHeader(name: string, idx?: number): any | undefined;
    /**
     * Message Header attribute selector. Alias of parseHeader.
     * @param name - header name
     * @param idx - header index
     * @returns Parsed header object, undefined if the
     *   header is not present or in case of a parsing error.
     *
     * @example
     * message.s('via',3).port
     */
    s(name: string, idx?: number): any | undefined;
    /**
     * Replace the value of the given header by the value.
     * @param name - header name
     * @param value - header value
     */
    setHeader(name: string, value: string): void;
    toString(): string;
}
export interface OutgoingRequestDelegate {
    /**
     * Received a 2xx positive final response to this request.
     * @param response - Incoming response.
     */
    onAccept?(response: IncomingResponse): void;
    /**
     * Received a 1xx provisional response to this request. Excluding 100 responses.
     * @param response - Incoming response.
     */
    onProgress?(response: IncomingResponse): void;
    /**
     * Received a 3xx negative final response to this request.
     * @param response - Incoming response.
     */
    onRedirect?(response: IncomingResponse): void;
    /**
     * Received a 4xx, 5xx, or 6xx negative final response to this request.
     * @param response - Incoming response.
     */
    onReject?(response: IncomingResponse): void;
    /**
     * Received a 100 provisional response.
     * @param response - Incoming response.
     */
    onTrying?(response: IncomingResponse): void;
}
export interface SimpleUserDelegate {
    /**
     * Called when a call is answered.
     * @remarks
     * Callback for handling establishment of a new Session.
     */
    onCallAnswered?(): void;
    /**
     * Called when a call is created.
     * @remarks
     * Callback for handling the creation of a new Session.
     */
    onCallCreated?(): void;
    /**
     * Called when a call is received.
     * @remarks
     * Callback for handling incoming INVITE requests.
     * The callback must either accept or reject the incoming call by calling `answer()` or `decline()` respectively.
     */
    onCallReceived?(): void;
    /**
     * Called when a call is hung up.
     * @remarks
     * Callback for handling termination of a Session.
     */
    onCallHangup?(): void;
    /**
     * Called when a call is put on hold or taken off hold.
     * @remarks
     * Callback for handling re-INVITE responses.
     */
    onCallHold?(held: boolean): void;
    /**
     * Called when a call receives an incoming DTMF tone.
     * @remarks
     * Callback for handling an incoming INFO request with content type application/dtmf-relay.
     */
    onCallDTMFReceived?(tone: string, duration: number): void;
    /**
     * Called upon receiving a message.
     * @remarks
     * Callback for handling incoming MESSAGE requests.
     * @param message - The message received.
     */
    onMessageReceived?(message: string): void;
    /**
     * Called when user is registered to received calls.
     */
    onRegistered?(): void;
    /**
     * Called when user is no longer registered to received calls.
     */
    onUnregistered?(): void;
    /**
     * Called when user is connected to server.
     * @remarks
     * Callback for handling user becomes connected.
     */
    onServerConnect?(): void;
    /**
     * Called when user is no longer connected.
     * @remarks
     * Callback for handling user becomes disconnected.
     *
     * @param error - An Error if server caused the disconnect. Otherwise undefined.
     */
    onServerDisconnect?(error?: Error): void;
}
export interface SipClientOptions {
    remoteAudio: HTMLAudioElement;
    userAuthNumber: string;
    userAuthPassword: string;
    iceGatheringTimeout?: number;
    delegate: SimpleUserDelegate;
    sipConfig: {
        host: string;
        port: number;
    };
    wsConfig: {
        path: string;
    };
}

export declare class SipClient {
    constructor(opts: SipClientOptions);
    answer(): Promise<void>;
    call(number: string | number, delegate: OutgoingRequestDelegate): Promise<void>;
    get isConnected(): boolean;
    connect(): Promise<void>;
    diconnect(): Promise<void>;
    register(delegate: OutgoingRequestDelegate): Promise<void>;
    unregister(): Promise<void>;
    hangup(): Promise<void>;
    hold(): Promise<void>;
    unhold(): Promise<void>;
    get isHeld(): boolean;
    mute(): void;
    unmute(): void;
    get isMuted(): boolean;
}

export {};

